name: Dashboard App

on:
  workflow_dispatch:

jobs:
  dashboard:
    name: "Build and push dashboard app to GitHub Pages folder"
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build dashboard
        run: |
          npm install --production
          PUBLIC_URL=https://automattic.github.io/jetpack-e2e-reports npm run build
          rm -rf docs/static/
          cp -a ./build/. docs/

      - name: Push changes
        env:
          MESSAGE: "Deployed dashboard app"
        run: ./bin/push-changes.sh
