name: Cleanup

on:
  workflow_dispatch:

  workflow_run:
    workflows: [Report]
    types:
      - completed

permissions:
  contents: read

concurrency:
  group: cleanup

jobs:
  report:
    name: "Clean up old results"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Install dependencies
        run: npm install

      - name: Clean up
        run: node ./bin/cleanup-s3.js
