name: Daily stats

on:
  schedule:
    - cron: '0 0,12 * * *' # run every day at 0 and 12 server time (UTC)

  workflow_dispatch:

jobs:
  report:
    name: "Create time stats"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Create stats
        run: node ./bin/recreate-time-stats.js
