name: Get test results

on: repository_dispatch

jobs:
  get-results:
    name: "Create new test reports"
    runs-on: ubuntu-latest

    steps:
      - name: Print event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
          echo ${{ toJson(github.event.client_payload) }}
          
      - name: Download test artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: Automattic/jetpack
          workflow: e2e-tests.yml
          # We may want to trigger this immediatly after test artefacts are uploaded 
          # and the workflow may continue and not be completed yet
          workflow_conclusion: "completed,in_progress"
          run_id: ${{ github.event.client_payload.run_id }}
          # run number from the workflow
          ##run_number: 34
          # Directory where to extract artifacts
          path: downloads
          
      # temp step to check download. delete me in final version
      - name: Upload test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-output
          path: downloads
          
      - name: Checkout reports branch
        run: echo "Checkout reports branch"
        
      - name: Copy new test results
        run: echo "Copy new test results"
        
      - name: Clean up old results
        run: echo "Clean up old results"
        
      - name: Generate new test report
        run: echo "Generate new test report"
        
      - name: Push changes
        run: echo "Push changes"
        
      - name: Send notification
        run: echo "Send Slack notification"
