name: Performance Report

on:
  repository_dispatch:
    types: [block-perf]

  workflow_dispatch:
    inputs:
      runId:
        description: 'Run ID'
        required: true
        default: '986899084'
      repository:
        description: 'Repository'
        required: true
        default: 'automattic/jetpack'
jobs:
  report:
    name: "Create new test report"
    runs-on: ubuntu-latest
    env:
      RUN_ID: ${{ github.event.client_payload.run_id }}
      REPOSITORY: ${{ github.event.client_payload.repository }}
      CLIENT_PAYLOAD: ${{ toJson(github.event.client_payload) }}

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Event information
        run: |
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"

          if [ "$GITHUB_EVENT_NAME" == workflow_dispatch ]; then
            echo "RUN_ID=${{ github.event.inputs.runId }}" >> $GITHUB_ENV
            echo "REPOSITORY=${{ github.event.inputs.repository }}" >> $GITHUB_ENV
          else
            echo "Received event '${{ github.event.action }}'"
            echo $CLIENT_PAYLOAD
          fi

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Wait for artifacts to be available
        run: ./bin/wait-for-artifacts.sh

      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: ${{ env.REPOSITORY }}
          workflow: block-performance.yml
          workflow_conclusion: "completed"
          run_id: ${{ env.RUN_ID }}
          path: ../downloads

      - name: Install dependencies
        run: npm install

      - name: Generate performance report
        env:
          RESULTS_PATH: ../downloads
        run: node ./bin/generate-perf-report.js
