name: Performance Report

on:
  repository_dispatch:
    types: [block-perf]
jobs:
  report:
    name: "Create new test report"
    runs-on: ubuntu-latest
    env:
      RUN_ID: ${{ github.event.client_payload.run_id }}
      REPOSITORY: ${{ github.event.client_payload.repository }}
      CLIENT_PAYLOAD: ${{ toJson(github.event.client_payload) }}

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2

      # - name: Event information
      #   run: |
      #     echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"

      #     if [ "$GITHUB_EVENT_NAME" == workflow_dispatch ]; then
      #       echo "RUN_ID=${{ github.event.inputs.runId }}" >> $GITHUB_ENV
      #       echo "PR_NUMBER=${{ github.event.inputs.pr }}" >> $GITHUB_ENV
      #       echo "BRANCH=${{ github.event.inputs.branch }}" >> $GITHUB_ENV
      #       echo "REPORT_NAME=${{ github.event.inputs.report_name }}" >> $GITHUB_ENV
      #       echo "REPOSITORY=${{ github.event.inputs.repository }}" >> $GITHUB_ENV
      #       echo "CLIENT_PAYLOAD={ \"branch\": \"${{ github.event.inputs.branch }}\", \"pr_number\": \"${{ github.event.inputs.pr }}\", \"pr_title\": \"${{ github.event.inputs.pr_title }}\", \"report_name\": \"${{ github.event.inputs.report_name }}\", \"repository\": \"${{ github.event.inputs.repository }}\", \"run_id\": \"${{ github.event.inputs.runId }}\", \"run_number\": \"000\" }" >> $GITHUB_ENV
      #     else
      #       echo "Received event '${{ github.event.action }}'"
      #     echo $CLIENT_PAYLOAD
      #     fi

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Wait for artifacts to be available
        run: ./bin/wait-for-artifacts.sh

      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: ${{ env.REPOSITORY }}
          workflow: e2e-tests.yml
          workflow_conclusion: "completed"
          run_id: ${{ env.RUN_ID }}
          path: ../downloads

      - name: Generate new test report
        env:
          RESULTS_PATH: ../downloads
          SITE_ROOT: docs
        run: ls -la $RESULTS_PATH

      # - name: Push changes
      #   env:
      #     MESSAGE: "New test report"
      #   run: ./bin/push-changes.sh
